version: '3.5'

services:

    kong-db:
      image: postgres:9.6
      networks:
        kong-net:
          aliases: 
            - kong-db
      ports:
        - "5432:5432"
      environment:
        - 'POSTGRES_DB=kong'
        - 'POSTGRES_USER=kong'
        - 'POSTGRES_PASSWORD=${KONG_POSTGRES_PASSWORD:-kong}'

    kong-migrations:
      image: kong:${KONG_VERSION:-2.0.1}
      networks:
        kong-net:
          aliases:
              - kong-migrations
      environment:
          - 'KONG_DATABASE=postgres'
          - 'KONG_PG_HOST=kong-db'
          - 'KONG_PG_PASSWORD=${KONG_POSTGRES_PASSWORD:-kong}'
      command: 
        - kong 
        - migrations 
        - bootstrap
      depends_on:
        - kong-db
  
    kong:
      image: kong:${KONG_VERSION:-2.0.1}
      networks:
        kong-net:
          aliases:
              - kong
      ports:
          - "8000:8000"
          - "8001:8001"
          - "8443:8443"
          - "8444:8444"
      environment:
          - 'KONG_DATABASE=postgres'
          - 'KONG_PG_HOST=kong-db'
          - 'KONG_PG_PASSWORD=${KONG_POSTGRES_PASSWORD:-kong}'
          - 'KONG_PROXY_ACCESS_LOG=/dev/stdout'
          - 'KONG_ADMIN_ACCESS_LOG=/dev/stdout'
          - 'KONG_PROXY_ERROR_LOG=/dev/stderr'
          - 'KONG_ADMIN_ERROR_LOG=/dev/stderr'
          - 'KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl'
      restart: on-failure
      depends_on:
          - kong-db
          - kong-migrations

    kuma-control-plane:
      image: kuma/kuma-cp:0.3.2
      volumes:
        - ./certs/server:/certs/server
        - ./certs/client/cert.pem:/certs/client/cert.pem
        - ./config:/etc/kuma
      command:
        - run
        - -c=/etc/kuma/kuma-cp.defaults.yaml
        - --log-level=debug
      environment:
        - KUMA_GENERAL_ADVERTISED_HOSTNAME=kuma-control-plane
        - KUMA_DATAPLANE_TOKEN_SERVER_PUBLIC_ENABLED=true
        - KUMA_DATAPLANE_TOKEN_SERVER_PUBLIC_INTERFACE=0.0.0.0
        - KUMA_DATAPLANE_TOKEN_SERVER_PUBLIC_PORT=5684 # otherwise there would be conflict with local port
        - KUMA_DATAPLANE_TOKEN_SERVER_PUBLIC_TLS_CERT_FILE=/certs/server/cert.pem
        - KUMA_DATAPLANE_TOKEN_SERVER_PUBLIC_TLS_KEY_FILE=/certs/server/key.pem
        - KUMA_DATAPLANE_TOKEN_SERVER_PUBLIC_CLIENT_CERTS_DIR=/certs/client
      ports:
        - "5678:5678"
        - "5679:5679"
        - "5680:5680"
        - "5681:5681"
        - "5682:5682"
        - "5683:5683"
        - "5684:5684"
      networks:
        kong-net:
          aliases:
            - kuma-control-plane
      restart: on-failure

networks:
  kong-net: {}